### ISSUE TITLE
Installer doesn't seem to install `blnsrv.exe` or `Balloon Service`

### ISSUE THREAD

**Issue by qqii** [virtio-win/virtio-win-guest-tools-installer#22]
The installer doesn't seem to copy `blnsrv.exe` or install the Balloon Service.

**Comment by milsav92** [comment]
Hi @qqii, are you running the installer on Windows Server 2022?

I've noticed that the `virtio-win-drivers-installer/constants.wxi.in` doesn't contain the 2022 version so it runs and succeeds but doesn't install any of the services or files in Program Files (I think it only creates the net folder).

As a **_UNSAFE_** workaround for Server 2022 you can change `HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\ProductName` (see `virtio-win-drivers-installer/properties.wxs`) to contain 2019 instead of 2022 and revert it back to the original after installation.

PS. @vrozenfe is it possible to add an installer warning screen notifying the user that the OS is unsupported? Because right now the installation will succeed for Server 2022 but no services will be installed (drivers are installed).

Also Win 11 reports itself as Windows 10 in the registry key above, so could the installer have an advanced button where the users could select a suitable version to install (as a drop down menu of all the available driver versions)?

**Comment by vrozenfe** [comment]
@milsav92 

We are going to add WS2022/Win11 support soon.

Vadim.

**Comment by chriscarpenter12** [comment]
Is there a time frame on "soon"? Is that published anywhere?

**Comment by vrozenfe** [comment]
Not published yet. 
There is a certain testing and validation process which needs to be completed before releasing the drivers for the new OS version. 

You can subscribe yourself to the following bug and watch the progress
https://bugzilla.redhat.com/show_bug.cgi?id=1995479

Regards,
Vadim.

**Comment by qqii** [comment]
Yes, I was running Server 2022. As suggested using to 2019 `blnsrv.exe` worked, except I copied it to the location manually. 

How do I subscribe on bugzilla?

**Comment by vrozenfe** [comment]
@qqii 
You should be able to add yourself to CC List on the bug's page.
In any case the problem should be fixed in build 215-2. 
Please visit https://github.com/virtio-win/kvm-guest-drivers-windows/issues/696 for more details.

Vadim.
